import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import ContainerBox from '../components/ContainerBox'
import HamburgerMenu from '../components/HamburgerMenu'
import Header from '../components/HeaderComponent/Header'

export default function Home() {
  const [hamburgerModal, sethamburgerModal] = useState(false)
  return (
    <div className='w-screen h-screen px-5 py-5 font-poppins'>
      <Head>
        <title>Rarible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital@0;1&display=swap"
      rel="stylesheet"
    />
      </Head >
      <Header sethamburgerModal={sethamburgerModal} hamburgerModal={hamburgerModal} />
      {hamburgerModal?<HamburgerMenu />:<ContainerBox/>}
    </div>
  )
}
